import * as path from 'node:path';
import { conf } from './src/conf.js';
conf.load(path.resolve('.'), path.resolve('./custom'), path.resolve('./custom/conf/app.ini'));
import { verifyLFSToken, mintLFSToken } from './src/lfsx.js';
const t = process.argv[2];
console.log('token under test:', t);
console.log('verify:', JSON.stringify(verifyLFSToken(t)));
const m = mintLFSToken(1, 1);
console.log('minted:', m.token);
console.log('minted parts:', m.token.split('.'));
