// First-run install wizard (GET/POST /install) writing custom/conf/app.ini.
import * as fs from 'node:fs';
import * as path from 'node:path';
import type { Context } from '../context.js';
import { conf } from '../conf.js';
import { db } from '../db/db.js';
import { gitVersion } from '../gitx/git.js';

function checkRunMode(c: Context): boolean {
  if (conf.installLock) {
    // locked installs hand the request to the SPA (renders its own 404)
    c.ServeWeb(404);
    return false;
  }
  return true;
}

export async function Install(c: Context): Promise<void> {
  if (!checkRunMode(c)) return;
  let gitVer = '';
  try {
    gitVer = await gitVersion();
  } catch {
    gitVer = '';
  }
  c.rendered = true;
  c.res.setHeader('Content-Type', 'text/html; charset=utf-8');
  const esc = (s: string) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  c.res.end(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"><title>Install - ${esc(conf.brandName)}</title>
<link rel="stylesheet" href="${conf.subpath}/css/semantic-2.4.2.min.css">
<style>body{background:#f5f5f5}.installer{max-width:640px;margin:48px auto}.field label{font-weight:600}</style>
</head>
<body>
<div class="installer">
<h1>${esc(conf.brandName)}: Install Your Own Git Service</h1>
<form class="ui form segment" method="post" action="${conf.subpath}/install">
<h4>General</h4>
<div class="field"><label>Application Name</label><input name="app_name" value="Gogs" placeholder="Name your app"></div>
<div class="field"><label>Application URL</label><input name="app_url" value="${esc(conf.externalURL)}" required></div>
<h4>Database</h4>
<div class="field"><label>Database Type</label>
<select name="db_type"><option value="sqlite3">SQLite3</option></select></div>
<h4>Repository Storage</h4>
<div class="field"><label>Repository Root Path</label><input name="repo_root_path" value="${esc(conf.repositoryRoot)}" required></div>
<div class="field"><label>Run User</label><input name="run_user" value="${esc(conf.runUser)}"></div>
<h4>Administrator Account (optional)</h4>
<div class="field"><label>Username</label><input name="admin_name"></div>
<div class="field"><label>Email</label><input name="admin_email" type="email"></div>
<div class="field"><label>Password</label><input name="admin_passwd" type="password"></div>
<h4>Options</h4>
<div class="ui checkbox"><input name="disable_registration" type="checkbox"><label>Disable self-registration</label></div>
<div class="ui checkbox"><input name="require_signin_view" type="checkbox"><label>Require sign-in to view</label></div>
<p>Git version: ${esc(gitVer)}</p>
<button class="ui blue button" type="submit">Install ${esc(conf.brandName)}</button>
</form>
</div>
</body></html>`);
}

export async function InstallPost(c: Context): Promise<void> {
  if (!checkRunMode(c)) return;
  const form = await c.form();
  const dbType = String(form.db_type ?? 'sqlite3');
  const appURL = String(form.app_url ?? conf.externalURL).replace(/\/?$/, '/');
  const repoRoot = String(form.repo_root_path ?? conf.repositoryRoot);
  const runUser = String(form.run_user ?? conf.runUser);
  const domain = (() => {
    try {
      return new URL(appURL).hostname;
    } catch {
      return conf.domain;
    }
  })();
  const port = (() => {
    try {
      return new URL(appURL).port || '3000';
    } catch {
      return String(conf.httpPort);
    }
  })();

  if (dbType !== 'sqlite3') {
    c.RenderWithErr(c.Tr('install.only_sqlite_supported'), 'install');
    return;
  }

  // validate repo root writable
  try {
    fs.mkdirSync(repoRoot, { recursive: true });
    fs.accessSync(repoRoot, fs.constants.W_OK);
  } catch {
    c.RenderWithErr(c.Tr('install.invalid_repo_path'), 'install');
    return;
  }

  const dbPath = path.join(conf.workDir, 'data', 'gogs.db');
  fs.mkdirSync(path.dirname(dbPath), { recursive: true });

  const adminName = String(form.admin_name ?? '');
  const adminEmail = String(form.admin_email ?? '');
  const adminPass = String(form.admin_passwd ?? '');

  const ini = `# Generated by ts-gogs install
APP_NAME = ${String(form.app_name ?? 'Gogs')}
RUN_USER = ${runUser}
RUN_MODE = prod

[server]
PROTOCOL = http
DOMAIN = ${domain}
HTTP_ADDR = 0.0.0.0
HTTP_PORT = ${port}
EXTERNAL_URL = ${appURL}
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false
APP_DATA_PATH = data
LANDING_URL = /

[database]
TYPE = sqlite3
PATH = ${dbPath}

[security]
INSTALL_LOCK = true
SECRET_KEY = ${(await import('node:crypto')).randomBytes(15).toString('hex')}
LOGIN_REMEMBER_DAYS = 7
COOKIE_USERNAME = i_like_gogs
COOKIE_REMEMBER_NAME = gogs_incredible
REVERSE_PROXY_AUTHENTICATION_USER = X-Forwarded-User

[repository]
ROOT = ${repoRoot}
SCRIPT_TYPE = bash
FORCE_PRIVATE = false
DEFAULT_BRANCH = master

[auth]
ACTIVE_CODE_LIVE_MINUTES = 180
RESET_PASSWD_CODE_LIVE_MINUTES = 180
REQUIRE_EMAIL_CONFIRMATION = false
DISABLE_REGISTRATION = ${String(form.disable_registration ?? '') === 'on' ? 'true' : 'false'}
ENABLE_REGISTRATION_CAPTCHA = true
REQUIRE_SIGNIN_VIEW = ${String(form.require_signin_view ?? '') === 'on' ? 'true' : 'false'}

[mailer]
ENABLED = false

[cron]
UPDATE_MIRRORS = false
`;
  fs.mkdirSync(path.dirname(conf.customConf), { recursive: true });
  fs.writeFileSync(conf.customConf, ini);

  // reload config + database with the new settings
  conf.load(conf.workDir, conf.customDir, conf.customConf);
  db(); // reopen schema with new path — db() memoizes, but path changed at first open too; fine on first run

  // create admin account when provided
  if (adminName && adminEmail) {
    try {
      const { createUser } = await import('../db/db.js');
      createUser(adminName, adminEmail, { password: adminPass, activated: true, admin: true });
    } catch (e: any) {
      c.RenderWithErr(String(e.message ?? e), 'install');
      return;
    }
  }

  c.flash.Success(c.Tr('install.install_success'));
  c.Redirect(conf.subpath + '/');
}
