// SSH public key parsing & fingerprints, mirroring gogs internal/database/ssh_key.go.
import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as db from '../db/db.js';
import { conf } from '../conf.js';

const AK_BEGIN = '# ts-gogs begin';
const AK_END = '# ts-gogs end';

/** Full path of the RUN_USER authorized_keys file. */
export function authorizedKeysPath(): string {
  return path.join(process.env.HOME ?? '/root', '.ssh', 'authorized_keys');
}

/** Runner command embedded into each key's command= restriction. */
function servRunner(keyID: number): string {
  const dist = path.join(conf.workDir, 'dist', 'index.js');
  const node = process.execPath;
  // NOTE: no inner quotes — the whole command is already inside the
  // authorized_keys command="..." value and nested quotes break parsing.
  if (fs.existsSync(dist)) {
    return `${node} ${dist} serv key-${keyID} --config=${conf.customConf}`;
  }
  return `${path.join(conf.workDir, 'node_modules', '.bin', 'tsx')} ${path.join(conf.workDir, 'src', 'index.ts')} serv key-${keyID} --config=${conf.customConf}`;
}

/**
 * Regenerate the RUN_USER authorized_keys: the ts-gogs marker block holds one
 * restricted entry per user key; lines outside the block are preserved.
 * (gogs RewriteAuthorizedKeys semantics, marker-scoped to be non-destructive.)
 */
export function writeAuthorizedKeys(): void {
  const file = authorizedKeysPath();
  fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });

  // existing content minus our previous marker block
  let existing: string[] = [];
  if (fs.existsSync(file)) {
    const raw = fs.readFileSync(file, 'utf8');
    let inBlock = false;
    for (const line of raw.split('\n')) {
      if (line.trim() === AK_BEGIN) { inBlock = true; continue; }
      if (line.trim() === AK_END) { inBlock = false; continue; }
      if (!inBlock && line.trim() !== '') existing.push(line);
    }
  }

  const keys = db.db().prepare('SELECT * FROM public_key WHERE type = 1').all() as any[];
  const block: string[] = [AK_BEGIN, `# Generated by ts-gogs at ${new Date().toISOString()}`];
  for (const key of keys) {
    const opts = `command="${servRunner(key.id)}",no-pty,no-port-forwarding,no-X11-forwarding,no-agent-forwarding`;
    block.push(`${opts} ${key.content}`);
  }
  block.push(AK_END);

  fs.writeFileSync(file, [...existing, ...block].join('\n') + '\n', { mode: 0o600 });
}

export async function checkPublicKey(content: string): Promise<string> {
  // validate via ssh-keygen if available, else structural check
  const parts = content.trim().split(/\s+/);
  if (parts.length < 2) throw new Error('invalid key');
  const types = ['ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'ssh-ed25519'];
  if (!types.includes(parts[0])) throw new Error('invalid key type');
  const body = Buffer.from(parts[1], 'base64');
  if (body.length === 0) throw new Error('invalid key body');
  return parts[0];
}

export function fingerprintKey(content: string): string {
  const parts = content.trim().split(/\s+/);
  const body = Buffer.from(parts[1] ?? '', 'base64');
  const md5fp = crypto.createHash('md5').update(body).digest('hex');
  return md5fp.replace(/(.{2})(?=.)/g, '$1:');
}

export async function addPublicKey(ownerID: number, name: string, content: string): Promise<void> {
  content = content.replaceAll('\n', '').replaceAll('\r', '').trim();
  if (!content) throw new Error('empty key content');
  await checkPublicKey(content);
  const fingerprint = fingerprintKey(content);
  const existing = db.db().prepare('SELECT 1 FROM public_key WHERE fingerprint = ?').get(fingerprint);
  if (existing) throw new Error('key content has been used');
  const existsName = db.db().prepare('SELECT 1 FROM public_key WHERE owner_id = ? AND name = ?').get(ownerID, name);
  if (existsName) throw new Error('key title has been used');
  db.db()
    .prepare('INSERT INTO public_key (owner_id, name, fingerprint, content, mode, type, created_unix, updated_unix) VALUES (?,?,?,?,2,1,?,?)')
    .run(ownerID, name, fingerprint, content, Math.floor(Date.now() / 1000), Math.floor(Date.now() / 1000));
  writeAuthorizedKeys();
}
