// SSH public key parsing & fingerprints, mirroring gogs internal/database/ssh_key.go.
import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as db from '../db/db.js';
import { conf } from '../conf.js';

export function writeAuthorizedKeys(): void {
  const keys = db.db().prepare('SELECT * FROM public_key').all() as any[];
  const lines: string[] = [
    `# Generated by ts-gogs at ${new Date().toISOString()}`,
    `# Heads up: any key added here is overwritten on next regeneration`,
  ];
  for (const key of keys) {
    if (key.type === 2) continue; // deploy keys not in authorized_keys
    lines.push(`no-pty,no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-command-aliases ${key.content}`);
  }
  fs.mkdirSync(path.dirname(sshHomePath()), { recursive: true });
  fs.appendFileSync(sshHomePath(), '');
  fs.writeFileSync(path.join(path.dirname(sshHomePath()), 'authorized_keys'), lines.join('\n') + '\n');
}

function sshHomePath(): string {
  return path.join(process.env.HOME ?? '/root', '.ssh', 'authorized_keys_gogs_placeholder');
}

export async function checkPublicKey(content: string): Promise<string> {
  // validate via ssh-keygen if available, else structural check
  const parts = content.trim().split(/\s+/);
  if (parts.length < 2) throw new Error('invalid key');
  const types = ['ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'ssh-ed25519'];
  if (!types.includes(parts[0])) throw new Error('invalid key type');
  const body = Buffer.from(parts[1], 'base64');
  if (body.length === 0) throw new Error('invalid key body');
  return parts[0];
}

export function fingerprintKey(content: string): string {
  const parts = content.trim().split(/\s+/);
  const body = Buffer.from(parts[1] ?? '', 'base64');
  const md5fp = crypto.createHash('md5').update(body).digest('hex');
  return md5fp.replace(/(.{2})(?=.)/g, '$1:');
}

export async function addPublicKey(ownerID: number, name: string, content: string): Promise<void> {
  content = content.replaceAll('\n', '').replaceAll('\r', '').trim();
  if (!content) throw new Error('empty key content');
  await checkPublicKey(content);
  const fingerprint = fingerprintKey(content);
  const existing = db.db().prepare('SELECT 1 FROM public_key WHERE fingerprint = ?').get(fingerprint);
  if (existing) throw new Error('key content has been used');
  const existsName = db.db().prepare('SELECT 1 FROM public_key WHERE owner_id = ? AND name = ?').get(ownerID, name);
  if (existsName) throw new Error('key title has been used');
  db.db()
    .prepare('INSERT INTO public_key (owner_id, name, fingerprint, content, mode, type, created_unix, updated_unix) VALUES (?,?,?,?,2,1,?,?)')
    .run(ownerID, name, fingerprint, content, Math.floor(Date.now() / 1000), Math.floor(Date.now() / 1000));
  writeAuthorizedKeys();
}
